run-config:
  batch-size: 32
  local-epochs: 5  # Maximum requested epochs
  lr: 0.1
  
node-config:
  num-partitions: 10  # Number of clients/partitions
  # partition-id will be assigned automatically
  
power-config:
  power-decay-per-epoch: 5  # درصد کاهش شارژ در هر اپوک
  charging-power-increase: 10  # درصد افزایش شارژ در حالت شارژ
  delta-c-discharging: -0.05  # کاهش قدرت محاسباتی در حالت دشارژ
  delta-c-charging: +0.1  # افزایش قدرت محاسباتی در حالت شارژ
  charging-probability: 0.3  # احتمال دلتا سی برای شارژ شدن گوشی